name: deploy-docker

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy-docker:
    name: Deploy Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push AMD64, ARM64
        id: docker_build
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: |
            rdavidoff/twitch-channel-points-miner-v2:latest
          platforms: linux/amd64,linux/arm64
          build-args: BUILDX_QEMU_ENV=true

      # File size exceeds the maximum allowed 25000 bytes
      # - name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}
      #     repository: rdavidoff/twitch-channel-points-miner-v2

      - name: Image digest AMD64, ARM64
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Build and push ARMv7
        id: docker_build_armv7
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: |
            rdavidoff/twitch-channel-points-miner-v2:latest
          platforms: linux/arm/v7
          build-args: BUILDX_QEMU_ENV=true
          dockerfile: Dockerfile.arm32v7

      - name: Image digest ARMv7
        run: echo ${{ steps.docker_build_armv7.outputs.digest }}
